# Generated by Django 5.1.4 on 2025-01-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderImage",
        ),
    ]
