# Generated by Django 5.1.4 on 2025-01-06 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_delete_orderimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="material_height",
            field=models.FloatField(
                default=0.0, help_text="Height in feet"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="material_length",
            field=models.FloatField(default=0.0, help_text="Length in feet"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="material_width",
            field=models.FloatField(default=0.0, help_text="Width in feet"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="wood_cost",
            field=models.DecimalField(default=0.0,
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
