# Generated by Django 5.1.4 on 2025-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_material_height_order_material_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="material_height",
            field=models.FloatField(help_text="Height in feel"),
        ),
        migrations.AlterField(
            model_name="order",
            name="wood_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
