# Generated by Django 5.1.4 on 2025-01-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_order_material_height_alter_order_wood_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="carpenter",
            new_name="carpenter_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="carpenter_workers",
            new_name="carpenter_workers_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="main_manager",
            new_name="main_manager_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_stage",
            new_name="order_stage_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="wood",
            new_name="wood_id",
        ),
    ]
