# Generated by Django 5.1.4 on 2025-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_material"),
        ("order", "0006_rename_carpenter_order_carpenter_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="wood_id",
        ),
        migrations.AddField(
            model_name="order",
            name="wood_ids",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="inventory.material"
            ),
        ),
    ]
