# Generated by Django 5.1.4 on 2025-01-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_order_wood_id_order_wood_ids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="wood_ids",
            new_name="material_ids",
        ),
    ]
