# Generated by Django 5.1.4 on 2025-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_rename_wood_ids_order_material_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="material_height",
            field=models.FloatField(blank=True, help_text="Height in feel", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="material_length",
            field=models.FloatField(blank=True, help_text="Length in feet", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="material_width",
            field=models.FloatField(blank=True, help_text="Width in feet", null=True),
        ),
    ]
