# Generated by Django 5.1.4 on 2025-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_order_material_height_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="wood_cost",
            new_name="ongoing_expense",
        ),
        migrations.RemoveField(
            model_name="order",
            name="material_height",
        ),
        migrations.RemoveField(
            model_name="order",
            name="material_length",
        ),
        migrations.RemoveField(
            model_name="order",
            name="material_width",
        ),
        migrations.AddField(
            model_name="order",
            name="total_material_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
