# Generated by Django 5.1.4 on 2025-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_order_completed_processes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="enquiry_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("checking", "Checking"),
                    ("completed", "Completed)"),
                ],
                default="requested",
                help_text="Status of the enquiry",
                max_length=20,
            ),
        ),
    ]
