# Generated by Django 5.1.4 on 2025-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_order_enquiry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ongoing_expense",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_material_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
