# Generated by Django 5.1.4 on 2025-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_alter_order_ongoing_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ongoing_expense",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_material_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
