# Generated by Django 5.1.4 on 2025-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_alter_order_ongoing_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
