# Generated by Django 5.1.4 on 2025-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_order_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="over_due",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry"),
                    ("on_going", "On Going"),
                    ("over_due", "Over due"),
                    ("completed", "Completed)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
