# Generated by Django 5.1.4 on 2025-01-13 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderimage'),
        ('process', '0014_processdetails_material_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_material_cost',
            new_name='material_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpenter_work_completion_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpenter_work_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpenter_work_hr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpenter_workers_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_stage_id',
        ),
        migrations.AddField(
            model_name='order',
            name='current_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_stage', to='process.process'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='carpenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpenter_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='main_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
