# Generated by Django 5.1.4 on 2025-01-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_rename_total_material_cost_order_material_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('on_going', 'On Going'), ('over_due', 'Over due'), ('completed', 'Completed)')], default='enquiry', max_length=10),
        ),
    ]
