# Generated by Django 5.1.4 on 2025-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enquiry_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('requested', 'Requested'), ('checking', 'Checking'), ('completed', 'Completed')], default='initiated', help_text='Status of the enquiry', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('on_going', 'On Going'), ('over_due', 'Over due'), ('completed', 'Completed'), ('archived', 'Archived')], default='enquiry', max_length=10),
        ),
    ]
