# Generated by Django 5.1.4 on 2025-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0021_alter_order_enquiry_status_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="current_process_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("on_going", "On going"),
                    ("completed", "Completed"),
                ],
                default="requested",
                help_text="Status of current process",
                max_length=20,
            ),
        ),
    ]
