# Generated by Django 5.1.4 on 2025-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0028_order_product_alter_review_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="voice_file",
            field=models.FileField(default="null", upload_to="voice_recordings/"),
            preserve_default=False,
        ),
    ]
