# Generated by Django 5.1.4 on 2025-03-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0029_order_voice_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="voice_file",
        ),
    ]
