# Generated by Django 5.1.4 on 2025-01-05 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='process',
            name='description_mal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='name_mal',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
