# Generated by Django 5.1.4 on 2025-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_process_name_mal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
