# Generated by Django 5.1.4 on 2025-01-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_process_name_mal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='description_mal',
        ),
        migrations.RemoveField(
            model_name='process',
            name='name_mal',
        ),
    ]
