# Generated by Django 5.1.4 on 2025-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_remove_process_description_mal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='name_mal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
