# Generated by Django 5.1.4 on 2025-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_process_name_mal'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description_mal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
