# Generated by Django 5.1.4 on 2025-01-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_process_description_mal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='name',
            new_name='process_name',
        ),
    ]
