# Generated by Django 5.1.4 on 2025-01-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_rename_name_process_process_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_name',
            new_name='name',
        ),
    ]
