# Generated by Django 5.1.4 on 2025-01-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_carpenter_id_alter_order_main_manager_id_and_more"),
        ("process", "0009_rename_process_name_process_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="requested",
                        help_text="Current status of the process",
                        max_length=20,
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(help_text="Expected date of process completion"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for the process",
                        max_digits=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image related to the process",
                        null=True,
                        upload_to="process_images/",
                    ),
                ),
                (
                    "main_manager_id",
                    models.ForeignKey(
                        help_text="Main manager responsible for this process",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_managed_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        help_text="Reference to the related order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_details",
                        to="order.order",
                    ),
                ),
                (
                    "process_id",
                    models.ForeignKey(
                        help_text="Reference to the process",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_details",
                        to="process.process",
                    ),
                ),
                (
                    "process_manager_id",
                    models.ForeignKey(
                        help_text="Manager overseeing this process",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_workers_id",
                    models.ManyToManyField(
                        help_text="Workers involved in the process",
                        related_name="worker_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
