# Generated by Django 5.1.4 on 2025-01-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_material"),
        ("process", "0010_processdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the material",
                        max_digits=10,
                    ),
                ),
                (
                    "material_id",
                    models.ForeignKey(
                        help_text="Reference to the material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_materials",
                        to="inventory.material",
                    ),
                ),
                (
                    "process_details_id",
                    models.ForeignKey(
                        help_text="Reference to the process details",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_materials",
                        to="process.processdetails",
                    ),
                ),
            ],
        ),
    ]
