# Generated by Django 5.1.4 on 2025-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0011_processmaterials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processdetails",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total price for the process",
                max_digits=10,
                null=True,
            ),
        ),
    ]
