# Generated by Django 5.1.4 on 2025-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0012_alter_processdetails_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdetails",
            name="over_due",
            field=models.BooleanField(default=0),
        ),
    ]
