# Generated by Django 5.1.4 on 2025-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0013_processdetails_over_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdetails",
            name="material_price",
            field=models.FloatField(default=0, help_text="Material price"),
        ),
        migrations.AddField(
            model_name="processdetails",
            name="workers_salary",
            field=models.FloatField(default=0, help_text="Workers Salary"),
        ),
        migrations.AddField(
            model_name="processmaterials",
            name="quantity",
            field=models.IntegerField(default=1, help_text="Quantity of the material"),
        ),
        migrations.AddField(
            model_name="processmaterials",
            name="total_price",
            field=models.FloatField(default=0.0, help_text="Total price"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processdetails",
            name="total_price",
            field=models.FloatField(default=0, help_text="Total price for the process"),
        ),
        migrations.AlterField(
            model_name="processmaterials",
            name="material_price",
            field=models.FloatField(help_text="Price of the material"),
        ),
    ]
