# Generated by Django 5.1.4 on 2025-01-26 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0014_processdetails_material_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdetails",
            name="request_accepted_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
