# Generated by Django 5.1.4 on 2025-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0015_processdetails_request_accepted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processdetails",
            name="request_accepted_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
