# Generated by Django 5.1.4 on 2025-01-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0016_alter_processdetails_request_accepted_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="process_details_images/")),
                (
                    "process_details_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="process.processdetails",
                    ),
                ),
            ],
        ),
    ]
