# Generated by Django 5.1.4 on 2025-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0017_orderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processdetails",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("verification", "Verification"),
                    ("overdue", "Overdue"),
                ],
                default="requested",
                help_text="Current status of the process",
                max_length=20,
            ),
        ),
    ]
