# Generated by Django 5.1.4 on 2025-01-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0018_alter_processdetails_process_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderImage",
            new_name="ProcessDetailsImage",
        ),
    ]
