# Generated by Django 5.1.4 on 2025-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0019_rename_orderimage_processdetailsimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdetails",
            name="completion_date",
            field=models.DateField(blank=True, help_text="Completion date", null=True),
        ),
    ]
