# Generated by Django 5.1.4 on 2025-01-28 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0020_processdetails_completion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="processdetails",
            name="process_started_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="process started date"
            ),
            preserve_default=False,
        ),
    ]
