# Generated by Django 5.1.4 on 2025-01-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("process", "0021_processdetails_process_started_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processdetails",
            name="process_started_date",
        ),
    ]
