# Generated by Django 5.1.4 on 2025-01-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_material"),
        ("order", "0009_alter_order_material_height_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpenterEnquire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_length",
                    models.FloatField(
                        blank=True, help_text="Length in feet", null=True
                    ),
                ),
                (
                    "material_height",
                    models.FloatField(
                        blank=True, help_text="Height in feet", null=True
                    ),
                ),
                (
                    "material_width",
                    models.FloatField(blank=True, help_text="Width in feet", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("checking", "Checking"),
                            ("responded", "Responded"),
                        ],
                        default="requested",
                        help_text="Status of the enquiry",
                        max_length=20,
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "carpenter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpenter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Materials",
                        to="inventory.material",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Reference to the related order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpenter_enquiries",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpenter Enquiry",
                "verbose_name_plural": "Carpenter Enquiries",
            },
        ),
    ]
