# Generated by Django 5.1.4 on 2025-01-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carpenter_work", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carpenterenquire",
            old_name="order",
            new_name="order_id",
        ),
    ]
