# Generated by Django 5.1.4 on 2025-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpenter_work", "0002_rename_order_carpenterenquire_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpenterenquire",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("checking", "Checking"),
                    ("completed", "Completed)"),
                ],
                default="requested",
                help_text="Status of the enquiry",
                max_length=20,
            ),
        ),
    ]
