# Generated by Django 5.1.4 on 2025-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0002_customuser_isadmin_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salary_per_hr",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
