# Generated by Django 5.1.4 on 2025-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0003_customuser_salary_per_hr"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enq_taker",
            field=models.BooleanField(default=False),
        ),
    ]
