# Generated by Django 5.1.4 on 2025-01-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.TextField(blank=True, null=True)),
                ('quality', models.TextField(blank=True, null=True)),
                ('durability', models.TextField(blank=True, null=True)),
                ('stock_availability', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.inventorycategory')),
            ],
        ),
    ]
