# Generated by Django 5.1.4 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
