# Generated by Django 5.1.4 on 2025-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_material_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
