# Generated by Django 5.1.4 on 2025-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_material_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="stock_availability",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
    ]
