# Generated by Django 5.1.4 on 2025-01-13 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_material_stock_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description_mal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='name_mal',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
