# Generated by Django 5.1.4 on 2025-01-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_material_description_mal_material_name_mal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.inventorycategory'),
        ),
    ]
