# Generated by Django 5.1.4 on 2025-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_material_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="material",
            name="name_mal",
            field=models.CharField(max_length=100),
        ),
    ]
