# Generated by Django 5.1.4 on 2025-02-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_material_code_alter_material_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="material_images/")),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_images",
                        to="inventory.material",
                    ),
                ),
            ],
        ),
    ]
