# Generated by Django 5.1.4 on 2025-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_materialimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="material_images/"
            ),
        ),
    ]
