# Generated by Django 5.1.4 on 2025-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_material_reference_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="mrp_in_gst",
            field=models.FloatField(default=0.0),
        ),
    ]
